import re

'''
Alternative filtering where only proteins from wanted organisms are included
'''

# path to \n separated list of wanted taxa
path_wanted_taxa = "wanted_organisms.txt"

# a list of the wanted taxa
wanted_taxa = open(path_wanted_taxa).read().strip().split('\n')

# The directory where the input file is and the output should be stored.
curdir = "<path_to_directory>"

# name of file generated by step 1
input_name = "<name.txt>"

# name to give to output file
output_name = "name.fasta"

# Put all sequences found by PSIBlast in a list
all = open(curdir+input_name).read().strip().split(">")[1:]

# Create a list to store the good entries only
filtered = []

# Give information to user what is happening
print("STARTING TAXON-FILTERING")
print("Seatching for following organisms:")
for taxon in wanted_taxa:
    print("\t'"+taxon+"'")

# Filter the sequences
print("RUNNING")
for entry in all:
    taxon = re.split("Tax=| TaxID=|OS=| OX=",entry)[1]
    if (re.search("|".join(wanted_taxa),taxon)): # criterion: organism name matches at least one of the wanted taxa
        filtered.append(entry)
print("FINISHED")

# Give information to user what was done and save result
print("Initial file had", len(all), "entries, filtered file has",len(filtered))
print("Creating new file: " + output_name)
out = open(curdir+output_name,"w")
for entry in filtered:
    out.write(">"+entry)
out.close()

